### ISSUE TITLE
LOL_v2_real权重

### ISSUE THREAD

**Issue by LongYu-LY** [XunpengYi/Diff-Retinex#1]
作者您好，非常感谢您的工作。
请问您有LOL_v2_real的权重吗？如果有的话能否分享一下。非常感谢

**Comment by LongYu-LY** [comment]
ImportError: cannot import name 'compute_img' from 'data.util'

**Comment by XunpengYi** [comment]
您好，我们没有在LOL_v2_real上训练过，暂时没有计划发布LOL_v2_real的预训练权重。如果有进一步的研究需要，我们可以考虑这个计划。感谢您的关注。

**Comment by XunpengYi** [comment]
您好，我们暂时没有计划发布LOL_v2_real的预训练权重。如果有进一步的研究需要，我们可以考虑这个计划。感谢您的关注！如有其他问题可以进一步描述。

**Comment by LongYu-LY** [comment]
好的，感谢您的回复

**Comment by XunpengYi** [comment]
我们已经更新了在LOL v2数据集上的权重，欢迎大家测试和使用。
